version: 2
updates:
  - package-ecosystem: nuget
    directory: /services/api
    schedule:
      interval: weekly
    groups:
      nuget:
        patterns: ['*']

  - package-ecosystem: pub
    directory: /apps/mobile
    schedule:
      interval: weekly
    groups:
      pub:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /tests/e2e
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /services/api
    schedule:
      interval: monthly
